cleaning

diff --git a/pyfirewall b/pyfirewall
--- a/pyfirewall
+++ b/pyfirewall
@@ -1,60 +1,69 @@
 #!/bin/bash
 #
-# PROGRAM-NAME: pyfirewall
-# VERSION: (Ver.0.12) Tuesday, 14 August 2012
-# DESCRIPTION: this is terminal command for run firewall in /etc/rc.d/rc.firewall
-# AUTHOR: Gianluca Pernigotto <jeanlucperni@gmail.com>
-# 
-# Copyright 2012  Gianluca PernigottoAll rights reserved.
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
 #
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
+#########################################################
+# Name: pyfirewall (main script)
+# Porpose: Main script pyfirewall runner
+# Writer: Gianluca Pernigoto <jeanlucperni@gmail.com>
+# Copyright: (c) 2013-2015 Gianluca Pernigoto <jeanlucperni@gmail.com>
+# license: GPL3
+# Version: (V0.12) Tuesday, 14 August 2012
+# Rev (v0.13) 06/02/2015
 #
-# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
-# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
-# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# DESCRIPTION:
+# This script is a convenient and reliable way for running the firewall 
+# daemon localized in /etc/rc.d/rc.firewall or /etc/init.d/firewall,
+# this depend what init-systems is used (System V or BSD style ?).
+# Also, it is check for a regular starting of pyfirewall program .
+##########################################################
 
+version=0.13
+path2=/etc/pyfirewall/$version
+path3=/etc/sysctl.conf
+
+# you must be root
 if [ $(id -u) -ne 0 ]; then
         echo -e "\nPermission denied\n"
         exit 1
 fi
 
-path1=/etc/rc.d/rc.firewall
-path2=/etc/pyfirewall/0.12
-path3=/etc/sysctl.conf
-
-if [ ! -e "$path1" ]; then
-	echo -e "[ERROR]: $path1\nFile di avvio mancante"
+# whereis firewall daemon? 
+if [ -e /etc/rc.d/rc.firewall ]; then
+	path1=/etc/rc.d/rc.firewall
+	
+elif [ -e /etc/init.d/firewall ]; then
+	path1=/etc/init.d/firewall
+	
+else
+	echo -e "[ERROR]: Can not find firewall daemon"
+	echo -e "This init system can not be supported"
 	exit 1
-elif [ ! -e "$path2/parser_loader" ]; then
-	echo -e "[ERROR]: $path2/parser_loader\nFile di configurazione mancante"
-	exit 1
-elif [ ! -e "$path2/rules_single_interface.conf" ]; then
-	echo -e "[ERROR]: $path2/rules_single_interface.conf\nFile di configurazione mancante"
-	exit 1
-elif [ ! -e "$path2/rules_multi_interfaces.conf" ]; then
-	echo -e "[ERROR]: $path2/rules_multi_interfaces.conf\nFile di configurazione mancante"
-	exit 1
-elif [ ! -e "$path3" ]; then
-	echo -e "[WARNING]: $path3\nFile mancante"
 fi
 
-bool=0
+
+# check existence files:
+if [ ! -e "$path2/parser_loader" ]; then
+	echo -e "[ERROR]: $path2/parser_loader\nNot exist"
+	exit 1
+elif [ ! -e "$path2/rules_single_interface.conf" ]; then
+	echo -e "[ERROR]: $path2/rules_single_interface.conf\nNot exist"
+	exit 1
+elif [ ! -e "$path2/rules_multi_interfaces.conf" ]; then
+	echo -e "[ERROR]: $path2/rules_multi_interfaces.conf\nNot exist"
+	exit 1
+elif [ ! -e "$path3" ]; then
+	echo -e "[WARNING]: $path3\nThis file not exist"
+fi
+
+bool=0 # is true
+
+# permission of execution value
 for n in {"$path1","$path2/parser_loader","$path2/rules_single_interface.conf","$path2/rules_multi_interfaces.conf"}                      
 do
 	if [ ! -x "$n" ]; then
-		bool=1
-		echo -e "\n [WARNING]: $n\n Manca il permesso di esecuzione."
-		echo -e " Non posso eseguire l'avvio del programma:"		
+		bool=1 # is false
+		echo -e "\n [WARNING]: $n\n Permission denied."
+		echo -e " Is not correctly set the execute permission:"
 	fi		
 done
 
@@ -62,8 +71,7 @@ if [ $bool = 1 ]; then
 	exit 1
 fi	
 
-
-/etc/rc.d/rc.firewall $1
+# run daemon
+$path1 $1
 
 exit 0
-
